module.exports = {
  // 登录
  LOGIN: {
    SET_SESSION_ID: 'LOGIN.SET_SESSION_ID',
    SET_WX_AUTH_ID: 'LOGIN.SET_WX_AUTH_ID'
  },
  // 用户
  USER: {
    SET_USER_INFO: 'USER.SET_USER_INFO',
    SET_WX_USER_INFO: 'USER.SET_WX_USER_INFO'
  },
  // 结算 -适用用品
  CHECKOUT: {
    SET_SETTLEMENT: 'CHECKOUT.SET_SETTLEMENT',
    SET_SCENETYPE: 'CHECKOUT.SET_SCENETYPE',
    SET_ADDRESS: 'CHECKOUT.SET_ADDRESS',
    SET_TYPE: 'CHECKOUT.SET_TYPE',
    SET_INVOICE: 'CHECKOUT.SET_INVOICE',
    SET_COUPON: 'CHECKOUT.SET_COUPON',
    SET_COUPON_DATA: 'CHECKOUT.SET_COUPON_DATA',
    SET_REMARK: 'CHECKOUT.SET_REMARK',
    CHANGE_REMARK: 'CHECKOUT.CHANGE_REMARK',
    RESET_STATE: 'CHECKOUT.RESET_STATE',
    SET_DIRECT_DATA: 'CHECKOUT.SET_DIRECT_DATA',
    SET_BALANCE: 'CHECKOUT.SET_BALANCE',
    SET_BALANCE_STATE: 'CHECKOUT.SET_BALANCE_STATE'
  },
  // 结算 -积分
  CHECKOUT_POINT: {
    SET_SETTLEMENT: 'CHECKOUT_POINT.SET_SETTLEMENT',
    SET_ADDRESS: 'CHECKOUT_POINT.SET_ADDRESS',
    SET_TYPE: 'CHECKOUT_POINT.SET_TYPE',
    SET_INVOICE: 'CHECKOUT_POINT.SET_INVOICE',
    SET_COUPON: 'CHECKOUT_POINT.SET_COUPON',
    SET_COUPON_DATA: 'CHECKOUT_POINT.SET_COUPON_DATA',
    SET_REMARK: 'CHECKOUT_POINT.SET_REMARK',
    CHANGE_REMARK: 'CHECKOUT_POINT.CHANGE_REMARK',
    RESET_STATE: 'CHECKOUT_POINT.RESET_STATE',
    SET_DIRECT_DATA: 'CHECKOUT_POINT.SET_DIRECT_DATA',
    SET_BALANCE: 'CHECKOUT_POINT.SET_BALANCE',
    SET_BALANCE_STATE: 'CHECKOUT_POINT.SET_BALANCE_STATE'
  }
}
